name: my_first_workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout github repo
              uses: actions/checkout@v4

            - name: checking some set of commands
              run: |
                echo "First hello"
                ls -alt
                cat README.md