name: my_first_workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout github repo
              uses: actions/checkout@v4
              
            - name: welcome message
              run: echo "First hello"

            - name: list files
              run: ls

            - name: read the file
              run: cat README.md