name: generate ascii

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout github repo
              uses: actions/checkout@v4

            - name: execute dragon_ascii script
              run: |
                chmod -R +x scripts/generate_ascii.sh
                cd scripts/generate_ascii.sh &&  ./generate_ascii.sh\
    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
            - name: test dragon_ascii script
              run: grep -i | "dragon" dragon.txt