name: generate ascii

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout github repo
              uses: actions/checkout@v4

            - name: execute dragon_ascii script
              run: |
                ls -alt
                chmod -R +x scripts/
                cd scripts &&  ./generate_ascii.sh
            - uses: actions/upload-artifact@v4
              with:
                name: dragon_pic
                path: scripts/dragon.txt
    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
            - name: download artifact
              uses: actions/download-artifact@v4
              with:
                name: dragon_pic
            - name: test dragon_ascii script
              run: |
                ls -alt
                grep -i "Dragon" dragon.txt